--超人『圣白莲』
function c26144.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetCountLimit(1,26144+EFFECT_COUNT_CODE_OATH)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetTarget(c26144.target)
	e1:SetOperation(c26144.activate)
	c:RegisterEffect(e1)
end
function c26144.filter(c)
	return c:IsSetCard(0x252a) and c:IsFaceup()
end
function c26144.target(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsLocation(LOCATION_MZONE) and chkc:IsControler(tp) and c26144.filter(chkc) end
	if chk==0 then return Duel.IsExistingTarget(c26144.filter,tp,LOCATION_MZONE,0,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_FACEUP)
	Duel.SelectTarget(tp,c26144.filter,tp,LOCATION_MZONE,0,1,1,nil)
end
function c26144.activate(e,tp,eg,ep,ev,re,r,rp)
	local tc=Duel.GetFirstTarget()
	local c=e:GetHandler()
	local res=RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END
	if not tc:IsRelateToEffect(e) or tc:IsFacedown() then return end
	if tc:IsType(TYPE_SYNCHRO) then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_SET_ATTACK_FINAL)
		e1:SetReset(res)
		e1:SetValue(tc:GetBaseAttack()*2)
		tc:RegisterEffect(e1)
		Duel.Hint(11,0,aux.Stringid(26144,1))
	elseif tc:IsType(TYPE_PENDULUM) then
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_EXTRA_ATTACK)
		e2:SetValue(1)
		e2:SetReset(res)
		tc:RegisterEffect(e2)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e3:SetCode(EFFECT_BATTLE_DESTROY_REDIRECT)
		e3:SetReset(res)
		e3:SetValue(LOCATION_DECKBOT)
		c:RegisterEffect(e3)
		Duel.Hint(11,0,aux.Stringid(26144,2))
	elseif tc:IsType(TYPE_RITUAL) then
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetCode(EFFECT_PIERCE)
		e4:SetReset(res)
		tc:RegisterEffect(e4)
		local e5=Effect.CreateEffect(c)
		e5:SetType(EFFECT_TYPE_SINGLE)
		e5:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
		e5:SetValue(1)
		e5:SetReset(res)
		tc:RegisterEffect(e5)
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_SINGLE)
		e6:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
		e6:SetValue(1)
		e6:SetReset(res)
		tc:RegisterEffect(e6)
		Duel.Hint(11,0,aux.Stringid(26144,3))
	elseif tc:IsType(TYPE_LINK) then
		local e7=Effect.CreateEffect(c)
		e7:SetType(EFFECT_TYPE_SINGLE)
		e7:SetCode(EFFECT_DIRECT_ATTACK)
		e7:SetReset(res)
		tc:RegisterEffect(e7)
		local e8=Effect.CreateEffect(c)
		e8:SetType(EFFECT_TYPE_SINGLE)
		e8:SetCode(EFFECT_ADD_SETCODE)
		e8:SetValue(0x251)
		e8:SetReset(res)
		tc:RegisterEffect(e8)
		Duel.Hint(11,0,aux.Stringid(26144,4))
	end
end
